### ISSUE TITLE
cannot import name 'util' from 'telebot' 

### ISSUE THREAD

**Issue by xuanvivo** [LlmKira/Openaibot#167]
2023-02-12 07-07-24: Traceback (most recent call last):
2023-02-12 07-07-24:   File "/root/my_app/Openaibot/Openaibot/main.py", line 52, in <module>
2023-02-12 07-07-24:     start()
2023-02-12 07-07-24:   File "/root/my_app/Openaibot/Openaibot/main.py", line 43, in start
2023-02-12 07-07-24:     module = importlib.import_module('App.' + starter)
2023-02-12 07-07-24:   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
2023-02-12 07-07-24:     return _bootstrap._gcd_import(name[level:], package, level)
2023-02-12 07-07-24:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2023-02-12 07-07-24:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2023-02-12 07-07-24:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2023-02-12 07-07-24:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2023-02-12 07-07-24:   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
2023-02-12 07-07-24:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2023-02-12 07-07-24:   File "/root/my_app/Openaibot/Openaibot/App/Telegram.py", line 17, in <module>
2023-02-12 07-07-24:     from telebot import util, types
2023-02-12 07-07-24: ImportError: cannot import name 'util' from 'telebot' (/root/my_app/.venv/lib/python3.9/site-packages/telebot/__init__.py)
2023-02-12 07-07-24: 2023-02-12 07:07:24.648 | INFO     | __main__:<module>:25 - NEWS Channel:https://t.me/Openaibot_channel

报错如上，python菜鸡一只，虚心请教一下。

另外 error: can't find Rust compiler

手动安装或是下载安装都一样报错

**Comment by sudoskys** [comment]
pip uninstall telebot
