### ISSUE TITLE
[Enhance] 升级到 ChatGpt 官方 Api

### ISSUE THREAD

**Issue by sudoskys** [LlmKira/Openaibot#179]
- [x] 接入一个项目 https://github.com/bytemate/chatapi-single

**Comment by emengweb** [comment]
这个太赞了，如果可以兼容，自用就没问题了，可以节省一笔费用

**Comment by sudoskys** [comment]
https://github.com/acheong08/ChatGPT/issues/776
v2 似乎已经不可用.... 寻找其他能正常的工作的框架中

**Comment by emengweb** [comment]
确实已经失效了，不过chatapi-single还是可用的，亲测部署成功速度还不错，普通账户也可以使用不消耗额度。

**Comment by sudoskys** [comment]
> 这个太赞了，如果可以兼容，自用就没问题了，可以节省一笔费用

已经合并此分支，你可以测试

**Comment by emengweb** [comment]
好的，下午测试下！点赞！

Jasmine ***@***.***> 于 2023年2月22日周三 10:19写道：

**Comment by emengweb** [comment]
可否提供配置信息呢？找不到在哪里开启这个api接口

**Comment by aiastia** [comment]
api是写啥

**Comment by emengweb** [comment]
> api是写啥

应该是自己搭建的chatapi-single地址

**Comment by emengweb** [comment]
按照这个设置格式配置的service.json
```
  "backend": {
    "type": "chatgpt",
    "openai": {
        "model": "text-davinci-003",
        "similarity_init": True,
        "token_limit": 4000
    },
    "chatgpt": {
        "api": "https://chat.xxx/",
        "agree": True
    }
  },
```
运行后报错
```
Traceback (most recent call last):
  File "/app/main.py", line 52, in 
    start()
  File "/app/main.py", line 43, in start
    module = importlib.import_module('App.' + starter)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "", line 1050, in _gcd_import
  File "", line 1027, in _find_and_load
  File "", line 1006, in _find_and_load_unlocked
  File "", line 688, in _load_unlocked
  File "", line 883, in exec_module
  File "", line 241, in _call_with_frames_removed
  File "/app/App/Telegram.py", line 22, in 
    from App import Event
  File "/app/App/Event.py", line 20, in 
    from utils.Chat import Utils, Usage, GroupManager, UserManager, Header, Style, ConfigUtils
  File "/app/utils/Chat.py", line 16, in 
    service = Service_Data.get_key()
  File "/app/utils/Data.py", line 346, in get_key
    _config = json.load(f)
  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 18 column 28 (char 314)
```

**Comment by emengweb** [comment]
设置了chatgpt，发现最终依旧是使用openai的key来进行通信，自己搭建的chatapi服务器未收到过任何请求

**Comment by sudoskys** [comment]
> 设置了chatgpt，发现最终依旧是使用openai的key来进行通信，自己搭建的chatapi服务器未收到过任何请求

奇怪，怎么会这样呢

**Comment by sudoskys** [comment]
有一个问题：我这边无法测试，我搭建不起来服务器

**Comment by sudoskys** [comment]
我记得没有 400 状态码啊？
![Screenshot_20230222_154133](https://user-images.githubusercontent.com/75739606/220554602-9c81a726-54d1-4776-85d9-288487fa5498.png)

**Comment by sudoskys** [comment]
是不是他采用的是和 Python 代理一样的反代服务，那个也是经过官方Api的ChatGpt模型

**Comment by sudoskys** [comment]
此问题在刚刚被尝试修复了

**Comment by emengweb** [comment]
> 

他项目的那个代理失效了，我再试试

**Comment by sudoskys** [comment]
+ 了None?

**Comment by sudoskys** [comment]
你可以测试一下吗？我这边没有环境可以调试...

**Comment by emengweb** [comment]
替换了最新的event.py，依旧是NoneType and str

**Comment by yanshibin** [comment]
他那个api连续对话好像有问题了

**Comment by emengweb** [comment]
连续对话没问题，uri格式/message/some-custem-str，其中some-custem-str代表一个特定id，在这个id下的对话就会延续。其实原理很简单，每使用一个新的some-custem-str就会在openai的web端开启一个新会话，这个可以同时登陆账号看下，删除会话直接提交DELETE方法就可以

**Comment by sudoskys** [comment]
> 替换了最新的event.py，依旧是NoneType and str

我这边没有测试环境，我构建失败了(Docker/Npm)

**Comment by emengweb** [comment]
可以pm我邮箱，我把我的环境地址发下给你哈

**Comment by LangInteger** [comment]
> [acheong08/ChatGPT#776](https://github.com/acheong08/ChatGPT/issues/776) v2 似乎已经不可用.... 寻找其他能正常的工作的框架中

其实还可以用，只是有时候他那个代理认证服务器挂了。后面还给出了自己搭代理认证服务器的代码：https://github.com/acheong08/ChatGPT/issues/776#issuecomment-1433934405

**Comment by sudoskys** [comment]
https://github.com/LlmKira/Openaibot/pull/207
