### ISSUE TITLE
gpt-3.5-turbo 和 gpt-3.5-turbo-0301的区别

### ISSUE THREAD

**Issue by Fangliding** [LlmKira/Openaibot#211]
文档里的backend似乎同时存在chatgpt和openai type里写的是chatgpt 我的理解是不是通过type指定模型类型然后现在是默认chatgpt
以及gpt-3.5-turbo和gpt-3.5-turbo-0301的区别是什么 搜了一圈没有资料

**Comment by Fangliding** [comment]
顺便我更新之后启动好像报错了(悲
`Traceback (most recent call last):
  File "main.py", line 52, in <module>
    start()
  File "main.py", line 43, in start
    module = importlib.import_module('App.' + starter)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in i
mport_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_lo
ad
  File "<frozen importlib._bootstrap>", line 975, in _find_and_lo
ad_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlock
ed
  File "<frozen importlib._bootstrap_external>", line 848, in exe
c_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_f
rames_removed
  File "/root/Openaibot/App/Telegram.py", line 22, in <module>
    from App import Event
  File "/root/Openaibot/App/Event.py", line 33, in <module>
    from llm_kira.creator import ThinkEngine, Hook
ImportError: cannot import name 'ThinkEngine' from 'llm_kira.crea
tor' (/usr/local/lib/python3.8/dist-packages/llm_kira/creator/__i
nit__.py)`

**Comment by sudoskys** [comment]
> 



> 文档里的backend似乎同时存在chatgpt和openai type里写的是chatgpt 我的理解是不是通过type指定模型类型然后现在是默认chatgpt 以及gpt-3.5-turbo和gpt-3.5-turbo-0301的区别是什么 搜了一圈没有资料

gpt-3.5-turbo-0301是版本固定的，另一个是持续更新的
